## 
## Set up  AWS Immersion Day
##
## Maintained by: John Park
##
version: '3.3'
services:
##
##
## Spin up the "loadgen" image. This image runs Apache and PHP and is
## the Cookbook is accessed and the data load generator lives.
## Apache is listening on port 80. Access at http://localhost 
##
   loadgen:
      image: attunitypm/loadgen:latest
      container_name: loadgen
      depends_on:
         - mysql
      environment:
         - DATASET=testdrive
         - HOSTROOT=localhost
         - PASSWORD=${PASSWORD}
      restart: always
      networks:
         - replnet

## Start MySQL. This will run on the replnet network. The database port will not be 
## exposed to the host.  You will need to connect via the  ip address of the 
## container. Hostname should be "mysqldb" and be visible to the Replicate server. 
## 
##
   mysql:
      image: mysql:5.7
      container_name: mysqldb
      restart: always
      environment:
         - MYSQL_ROOT_PASSWORD=${PASSWORD}
         - MYSQL_DATABASE=qlik_mysql
      restart: always
      volumes:
         - mysql-data:/var/lib/mysql
      ports:
         - 3306:3306
      networks:
         - replnet
      command: mysqld --datadir=/var/lib/mysql --user=mysql --server-id=1 --log-bin=mysql-bin.log --binlog-format=ROW --expire-logs-days=1 --default-storage-engine=InnoDB
##
## Start PostgreSQL. This will run on the replnet network. Database port will not be 
## exposed directly on localhost.  You will need to connect via the ip address of 
## the container. Hostname should be "postgresdb" and be visible to the Replicate 
## server. 
##
   postgres:
      image: postgres:9.6
      container_name: postgresdb
      environment:
         - POSTGRES_USER=${USERNAME}
         - POSTGRES_PASSWORD=${PASSWORD}
         - POSTGRES_DB=testdrive
         - PGDATA=/var/lib/postgresql/data
      restart: always
      volumes:
         - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
         - postgres-data:/var/lib/postgresql
      ports:
         - 5432:5432
      networks:
         - replnet
      command: -c wal_level=logical -c max_replication_slots=3 -c max_wal_senders=3 -c wal_sender_timeout=60s
##
## Start PGADMIN, listening on port 5430. This will run on the replnet network
## and will allow us to browse the postgres database.
##
#   pgadmin:
#      image: dpage/pgadmin4:latest
#      container_name: pgadmin
#      depends_on:
#         - postgres
#      environment:
#         - PGADMIN_DEFAULT_EMAIL=${LOGIN}
#         - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
#         - PGADMIN_LISTEN_PORT=5430
#      restart: always
#      volumes:
#         - pgadmin-data:/var/lib/pgadmin
#         - ./pgadmin.json:/pgadmin4/servers.json
#      ports:
#         - 5430:5430
#      networks:
#         - replnet
##
##
## run zookeeper. Needed for Kafka. Ports not exposed to localhost. Hostname 
## should be "zkhost" and be visible to the Replicate server.
##
   zookeeper:
      image: confluentinc/cp-zookeeper:4.0.0
      container_name: zkhost
      restart: always
      environment:
         - ZOOKEEPER_CLIENT_PORT=32181
         - ZOOKEEPER_TICK_TIME=2000
         - ZOOKEEPER_SYNC_LIMIT=2         
         - ZOOKEEPER_SERVER_ID=1
      ports:
         - 32181:32181
      networks:
         - replnet
##
## run Kafka. Requires zookeeper to be running. Ports not exposed to locahost. 
## Hostname should be "kafka" and should be visible to the Replicate server.
##
   kafka:
      image: confluentinc/cp-kafka:4.0.0
      container_name: kafka
      depends_on:
         - zookeeper
      restart: always
      environment:
         - KAFKA_ZOOKEEPER_CONNECT=zkhost:32181
         - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
         - KAFKA_BROKER_ID=1
         - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      ports:
         - 29092:29092
      networks:
         - replnet
##
## run the confluent schema registry. Requires zookeeper to be running. 
## Hostname should be "sreghost" and should be visible to the Replicate server.
##
   schema-registry:
      image: confluentinc/cp-schema-registry:4.0.0
      container_name: sreghost
      depends_on:
         - zookeeper
         - kafka
      restart: always
      environment:
         - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zkhost:32181
         - SCHEMA_REGISTRY_HOST_NAME=sreghost
         - SCHEMA_REGISTRY_LISTENERS=http://sreghost:8081
         - SCHEMA_REGISTRY_DEBUG=true
      ports:
         - 8081
      networks:
         - replnet
##
## run the Kafka REST proxy server
##
#   kafka-rest:
#      image: confluentinc/cp-kafka-rest:4.0.0
#      container_name: kafkarest
#      depends_on:
#         - schema-registry
#      environment:
#         - ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*"
#         - KAFKA_REST_ZOOKEEPER_CONNECT=zkhost:32181
#         - KAFKA_REST_LISTENERS=http://kafkarest:8082
#         - KAFKA_REST_SCHEMA_REGISTRY_URL=http://sreghost:8081
#         - KAFKA_REST_HOST_NAME=kafkarest
#         - KAFKA_REST_DEBUG=true
#         - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:29092
#         - KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS=30000
#      restart: always
#      ports:
#         - 8082:8082
#      networks:
#         - replnet
#kafdrop

   kafdrop:
      image: obsidiandynamics/kafdrop
      container_name: kafdrop
      restart: "no"
      ports:
         - 9000:9000
      networks:
         - replnet
      environment:
         KAFKA_BROKERCONNECT: "kafka:29092"
         JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      depends_on:
         - kafka
   sqlpad:
   # To use Dockerfile at root of this project, use build instead of image
   # build: ../../
      image: sqlpad/sqlpad:5
      container_name: sqlpad_aws
      hostname: 'sqlpad'
      ports:
         - '3000:3000'
      environment:
         SQLPAD_ADMIN: ${LOGIN}
         SQLPAD_ADMIN_PASSWORD: ${PASSWORD}
         SQLPAD_APP_LOG_LEVEL: debug
         SQLPAD_WEB_LOG_LEVEL: warn
         SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
         #SQLPAD_BACKEND_DB_URI: mysql://root:${PASSWORD}@mysqldb2:3306/qlik_mysql
         SQLPAD_SESSION_STORE: 'database'
         SQLPAD_DB_PATH: '/var/lib/sqlpad'
         SQLPAD_DB_IN_MEMORY: 'false'
         SQLPAD_QUERY_RESULT_STORE: 'database'
         SQLPAD_CONNECTIONS__pgdemo__name: postgres-dw
         SQLPAD_CONNECTIONS__pgdemo__driver: postgres
         SQLPAD_CONNECTIONS__pgdemo__host: postgresdb
         SQLPAD_CONNECTIONS__pgdemo__database: testdrive
         SQLPAD_CONNECTIONS__pgdemo__username: ${USERNAME}
         SQLPAD_CONNECTIONS__pgdemo__password: ${PASSWORD}
         SQLPAD_CONNECTIONS__mysql__name: 'mysql-source'
         SQLPAD_CONNECTIONS__mysql__driver: mysql
         SQLPAD_CONNECTIONS__mysql__host: mysqldb
         SQLPAD_CONNECTIONS__mysql__port: 3306
         SQLPAD_CONNECTIONS__mysql__database: testdrive
         SQLPAD_CONNECTIONS__mysql__username: root
         SQLPAD_CONNECTIONS__mysql__password: ${PASSWORD}
         # SQLPAD_CONNECTIONS__mariad__multiStatementTran
         SQLPAD_CONNECTIONS__pgdemo__multiStatementTransactionEnabled: 'true'
         SQLPAD_CONNECTIONS__pgdemo__idleTimeoutSeconds: 86400
      volumes:
         - sqlpad-data:/etc/sqlpad/seed-data
      networks:
         - replnet

volumes:
   postgres-data:
   pgadmin-data:
   sqlpad-data:
   mysql-data:
networks:
   replnet:
      driver: bridge
